import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, ExternalLink } from "lucide-react";
import { companyById, companyGuides, companySourceById } from "@/data/companies";
export const dynamicParams = false;
export function generateStaticParams() { return companyGuides.map((guide) => ({ company: guide.id })); }
export async function generateMetadata({ params }: { params: Promise<{ company: string }> }): Promise<Metadata> { const { company } = await params; const guide = companyById.get(company); return { title: guide ? `${guide.name} interview guide` : "Company guide", description: guide?.summary }; }
export default async function CompanyPage({ params }: { params: Promise<{ company: string }> }) { const { company } = await params; const guide = companyById.get(company); if (!guide) notFound(); return <main id="main-content" className="company-guide" data-pagefind-body><Link className="back-link" href="/companies/"><ArrowLeft size={16} /> All company guides</Link><header><div><span>{guide.archetype}</span><span>as of {guide.asOf}</span></div><h1>{guide.name}</h1><p>{guide.summary}</p></header><aside>{guide.disclaimer}</aside><section><h2>Preparation priorities</h2><ol>{guide.roleFocus.map((item) => <li key={item}>{item}</li>)}</ol></section><section><h2>Public-process preparation map</h2><div className="company-rounds">{guide.rounds.map((round, index) => <article key={round.title}><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{round.title}</h3><p>{round.format}</p><strong>Signals</strong><ul>{round.focus.map((item) => <li key={item}>{item}</li>)}</ul><strong>Prepare</strong><ul>{round.preparation.map((item) => <li key={item}>{item}</li>)}</ul></div></article>)}</div></section><section><h2>Source</h2>{guide.sourceIds.map((id) => { const source = companySourceById.get(id); return source ? <a key={id} href={source.url}>{source.title} <ExternalLink size={14} /></a> : null; })}</section></main>; }
