import type { Metadata } from "next";
import Link from "next/link";
import { SettingsClient } from "@/components/settings-client";
import { CONTENT_MANIFEST_VERSION, publishedTopics, topics } from "@/data/catalog";
import { companyArchetypes, mockLoops, practiceSets } from "@/data/practice-sets";
import { questions } from "@/data/questions";
import { technologies, commands } from "@/data/technologies";
import { dsaProblems, dsaSheets } from "@/data/dsa";
import { companyGuides } from "@/data/companies";
export const metadata: Metadata = { title: "Settings and offline packs" };
export default function SettingsPage() { return <main id="main-content" className="tool-page"><header className="tool-page-title"><h1>Offline and data controls</h1><p>Install content packs, keep versioned backups, move study history, and inspect the published corpus without an account.</p></header><SettingsClient /><section className="audit-field" aria-labelledby="audit-field-title"><header><div><h2 id="audit-field-title">Corpus audit</h2><p>Build-time validation blocks publication when contracts, relationships, sources, routes, or freshness checks fail.</p></div><span>{CONTENT_MANIFEST_VERSION}</span></header><dl><div><dt>Published field notes</dt><dd>{publishedTopics.length}</dd></div><div><dt>Technology manuals</dt><dd>{technologies.length}</dd></div><div><dt>Command examples</dt><dd>{commands.length}</dd></div><div><dt>DSA problems</dt><dd>{dsaProblems.length}</dd></div><div><dt>Nested DSA sheets</dt><dd>{dsaSheets.length}</dd></div><div><dt>Named company guides</dt><dd>{companyGuides.length}</dd></div><div><dt>Original topic questions</dt><dd>{questions.length}</dd></div><div><dt>Practice sets / mocks</dt><dd>{practiceSets.length} / {mockLoops.length}</dd></div><div><dt>Company archetypes</dt><dd>{companyArchetypes.length}</dd></div><div><dt>Manifest topics</dt><dd>{topics.length}</dd></div></dl><nav aria-label="Download corpus audit reports"><Link href="/generated/completeness-report.json">Completeness report</Link><Link href="/generated/content-freshness-report.json">Freshness report</Link><Link href="/generated/coverage-manifest.json">Coverage manifest</Link><Link href="/generated/pack-manifest.json">Offline pack manifest</Link></nav></section></main>; }
